import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

import Layout from "@/components/layout";

import { getAllPosts } from "@/utils/post";

export default function Home({ postData }) {
  console.log(postData);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Layout>
          <h1>Il Mio Blog</h1>

          {postData?.map((post, i) => (
            <h3 key={i}>{post?.title}</h3>
          ))}
        </Layout>
      </main>
    </>
  );
}
export const getStaticProps = () => {
  const postData = getAllPosts();

  return {
    props: {
      postData,
    },
  };
};
